--------------------------------------------------------
--  已建立檔案 - 星期六-三月-21-2020   
--------------------------------------------------------
DROP TABLE "DA106G5"."GROUP_RPT";
DROP TABLE "DA106G5"."GRP_DETAIL";
DROP TABLE "DA106G5"."GRP_FOLLOW";
DROP TABLE "DA106G5"."GROUPER";
--------------------------------------------------------
--  DDL for Table GROUPER
--------------------------------------------------------

  CREATE TABLE "DA106G5"."GROUPER" 
   (	"GRP_NO" VARCHAR2(20 BYTE), 
	"MB_ID" VARCHAR2(20 BYTE), 
	"LOC_NO" VARCHAR2(20 BYTE), 
	"GRP_APPLYSTART" DATE, 
	"GRP_APPLYEND" DATE, 
	"GRP_START" DATE, 
	"GRP_END" DATE, 
	"GRP_NAME" VARCHAR2(20 BYTE), 
	"GRP_CONTENT" VARCHAR2(400 BYTE), 
	"GRP_PERSONMAX" NUMBER(2,0), 
	"GRP_PERSONMIN" NUMBER(2,0), 
	"GRP_PERSONCOUNT" NUMBER(2,0), 
	"GRP_STATUS" NUMBER(1,0), 
	"GRP_FOLLOW" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GROUP_RPT
--------------------------------------------------------

  CREATE TABLE "DA106G5"."GROUP_RPT" 
   (	"GROUP_RPT_NO" VARCHAR2(20 BYTE), 
	"GRP_NO" VARCHAR2(20 BYTE), 
	"MB_ID" VARCHAR2(20 BYTE), 
	"RPT_REASON" CLOB, 
	"RPT_STATUS" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("RPT_REASON") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table GRP_DETAIL
--------------------------------------------------------

  CREATE TABLE "DA106G5"."GRP_DETAIL" 
   (	"MB_ID" VARCHAR2(20 BYTE), 
	"GRP_NO" VARCHAR2(20 BYTE), 
	"GRP_REGISTER" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GRP_FOLLOW
--------------------------------------------------------

  CREATE TABLE "DA106G5"."GRP_FOLLOW" 
   (	"GRP_NO" VARCHAR2(20 BYTE), 
	"MB_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_GROUP_RPT
--------------------------------------------------------

  CREATE UNIQUE INDEX "DA106G5"."PK_GROUP_RPT" ON "DA106G5"."GROUP_RPT" ("GROUP_RPT_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_GROUPER
--------------------------------------------------------

  CREATE UNIQUE INDEX "DA106G5"."PK_GROUPER" ON "DA106G5"."GROUPER" ("GRP_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

--------------------------------------------------------
--  DDL for Index PK_GRP_DETAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "DA106G5"."PK_GRP_DETAIL" ON "DA106G5"."GRP_DETAIL" ("MB_ID", "GRP_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_GRP_FOLLOW
--------------------------------------------------------

  CREATE UNIQUE INDEX "DA106G5"."PK_GRP_FOLLOW" ON "DA106G5"."GRP_FOLLOW" ("GRP_NO", "MB_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table GROUP_RPT
--------------------------------------------------------

  ALTER TABLE "DA106G5"."GROUP_RPT" ADD CONSTRAINT "PK_GROUP_RPT" PRIMARY KEY ("GROUP_RPT_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DA106G5"."GROUP_RPT" MODIFY ("RPT_STATUS" NOT NULL ENABLE);
  ALTER TABLE "DA106G5"."GROUP_RPT" MODIFY ("GROUP_RPT_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GROUPER
--------------------------------------------------------

  ALTER TABLE "DA106G5"."GROUPER" ADD CONSTRAINT "PK_GROUPER" PRIMARY KEY ("GRP_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DA106G5"."GROUPER" MODIFY ("GRP_FOLLOW" NOT NULL ENABLE);
  ALTER TABLE "DA106G5"."GROUPER" MODIFY ("GRP_STATUS" NOT NULL ENABLE);
  ALTER TABLE "DA106G5"."GROUPER" MODIFY ("GRP_PERSONCOUNT" NOT NULL ENABLE);
  ALTER TABLE "DA106G5"."GROUPER" MODIFY ("GRP_PERSONMIN" NOT NULL ENABLE);
  ALTER TABLE "DA106G5"."GROUPER" MODIFY ("GRP_NAME" NOT NULL ENABLE);
  ALTER TABLE "DA106G5"."GROUPER" MODIFY ("GRP_END" NOT NULL ENABLE);
  ALTER TABLE "DA106G5"."GROUPER" MODIFY ("GRP_START" NOT NULL ENABLE);
  ALTER TABLE "DA106G5"."GROUPER" MODIFY ("GRP_APPLYEND" NOT NULL ENABLE);
  ALTER TABLE "DA106G5"."GROUPER" MODIFY ("GRP_APPLYSTART" NOT NULL ENABLE);
  ALTER TABLE "DA106G5"."GROUPER" MODIFY ("GRP_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GRP_FOLLOW
--------------------------------------------------------

  ALTER TABLE "DA106G5"."GRP_FOLLOW" ADD CONSTRAINT "PK_GRP_FOLLOW" PRIMARY KEY ("GRP_NO", "MB_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DA106G5"."GRP_FOLLOW" MODIFY ("MB_ID" NOT NULL ENABLE);
  ALTER TABLE "DA106G5"."GRP_FOLLOW" MODIFY ("GRP_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GRP_DETAIL
--------------------------------------------------------

  ALTER TABLE "DA106G5"."GRP_DETAIL" ADD CONSTRAINT "PK_GRP_DETAIL" PRIMARY KEY ("MB_ID", "GRP_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DA106G5"."GRP_DETAIL" MODIFY ("GRP_REGISTER" NOT NULL ENABLE);
  ALTER TABLE "DA106G5"."GRP_DETAIL" MODIFY ("GRP_NO" NOT NULL ENABLE);
  ALTER TABLE "DA106G5"."GRP_DETAIL" MODIFY ("MB_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table GROUPER
--------------------------------------------------------

  ALTER TABLE "DA106G5"."GROUPER" ADD CONSTRAINT "FK_GROUPER_0" FOREIGN KEY ("MB_ID")
	  REFERENCES "DA106G5"."MEMBER" ("MB_ID") ENABLE;
  ALTER TABLE "DA106G5"."GROUPER" ADD CONSTRAINT "FK_GROUPER_1" FOREIGN KEY ("LOC_NO")
	  REFERENCES "DA106G5"."LOCATION" ("LOC_NO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GROUP_RPT
--------------------------------------------------------

  ALTER TABLE "DA106G5"."GROUP_RPT" ADD CONSTRAINT "FK_GROUP_RPT_0" FOREIGN KEY ("GRP_NO")
	  REFERENCES "DA106G5"."GROUPER" ("GRP_NO") ENABLE;
  ALTER TABLE "DA106G5"."GROUP_RPT" ADD CONSTRAINT "FK_GROUP_RPT_1" FOREIGN KEY ("MB_ID")
	  REFERENCES "DA106G5"."MEMBER" ("MB_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GRP_DETAIL
--------------------------------------------------------

  ALTER TABLE "DA106G5"."GRP_DETAIL" ADD CONSTRAINT "FK_GRP_DETAIL_0" FOREIGN KEY ("MB_ID")
	  REFERENCES "DA106G5"."MEMBER" ("MB_ID") ENABLE;
  ALTER TABLE "DA106G5"."GRP_DETAIL" ADD CONSTRAINT "FK_GRP_DETAIL_1" FOREIGN KEY ("GRP_NO")
	  REFERENCES "DA106G5"."GROUPER" ("GRP_NO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GRP_FOLLOW
--------------------------------------------------------

  ALTER TABLE "DA106G5"."GRP_FOLLOW" ADD CONSTRAINT "FK_GRP_FOLLOW_0" FOREIGN KEY ("GRP_NO")
	  REFERENCES "DA106G5"."GROUPER" ("GRP_NO") ENABLE;
  ALTER TABLE "DA106G5"."GRP_FOLLOW" ADD CONSTRAINT "FK_GRP_FOLLOW_1" FOREIGN KEY ("MB_ID")
	  REFERENCES "DA106G5"."MEMBER" ("MB_ID") ENABLE;
